# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpcDemo_pb2 as grpcDemo__pb2


class GrpcDemoStub(object):
    """定义进程之间调用的方法
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMessgae = channel.unary_unary(
                '/GrpcDemo/GetMessgae',
                request_serializer=grpcDemo__pb2.Request.SerializeToString,
                response_deserializer=grpcDemo__pb2.Response.FromString,
                )


class GrpcDemoServicer(object):
    """定义进程之间调用的方法
    """

    def GetMessgae(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcDemoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMessgae': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessgae,
                    request_deserializer=grpcDemo__pb2.Request.FromString,
                    response_serializer=grpcDemo__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GrpcDemo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcDemo(object):
    """定义进程之间调用的方法
    """

    @staticmethod
    def GetMessgae(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GrpcDemo/GetMessgae',
            grpcDemo__pb2.Request.SerializeToString,
            grpcDemo__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
